// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOzHJVk-4l4jI-YGVeNxPPpR6bFKtdqH4',
    appId: '1:91425891202:web:fd7a3d1521eba86547a59b',
    messagingSenderId: '91425891202',
    projectId: 'contacts-6c029',
    authDomain: 'contacts-6c029.firebaseapp.com',
    storageBucket: 'contacts-6c029.appspot.com',
    measurementId: 'G-NLGHQQMXD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lsdiE-Mvu_nVCL7PBcN0qw7eRBi4wMs',
    appId: '1:91425891202:android:90317f355f519f0c47a59b',
    messagingSenderId: '91425891202',
    projectId: 'contacts-6c029',
    storageBucket: 'contacts-6c029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4uQsyEaw_C_P3eKRX2GnsROkwk3ASm8',
    appId: '1:91425891202:ios:ddf974dd1e06f05b47a59b',
    messagingSenderId: '91425891202',
    projectId: 'contacts-6c029',
    storageBucket: 'contacts-6c029.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4uQsyEaw_C_P3eKRX2GnsROkwk3ASm8',
    appId: '1:91425891202:ios:ddf974dd1e06f05b47a59b',
    messagingSenderId: '91425891202',
    projectId: 'contacts-6c029',
    storageBucket: 'contacts-6c029.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOzHJVk-4l4jI-YGVeNxPPpR6bFKtdqH4',
    appId: '1:91425891202:web:3c808c32a172d36e47a59b',
    messagingSenderId: '91425891202',
    projectId: 'contacts-6c029',
    authDomain: 'contacts-6c029.firebaseapp.com',
    storageBucket: 'contacts-6c029.appspot.com',
    measurementId: 'G-V2VYDX55C0',
  );
}
